### ISSUE TITLE
Extend the custom curves JSON API to allow more curves

### ISSUE THREAD

**Issue by antw** [quintel/etengine#1143]
The list of allowed custom curves [is hard-coded in CustomCurvesController](https://github.com/quintel/etengine/blob/4b6eac9046a0d2173502d3e629b31a06972d8107/app/controllers/api/v3/custom_curves_controller.rb#L11-L18). To support user-defined profiles we should move this config to ETSource's "config" directory and [Atlas' `Config` module](https://github.com/quintel/atlas/blob/master/lib/atlas/config.rb).

Modellers should be able to define which curves can be customised by users, and any other data needed to configure the customisation, such as which handler to use, and which input is (optionally) set when the curve is uploaded. For example:

```yaml
- key: buildings_cooling
  handler: profile

- key: weather/air_temperature
  handler: temperature
  sets: solar_pv_flh_input_key

- key: weather/solar_pv
  handler: profile
  sets: solar_pv_flh_input_key
```

In addition, [the `index` action](https://github.com/quintel/etengine/blob/4b6eac9046a0d2173502d3e629b31a06972d8107/app/controllers/api/v3/custom_curves_controller.rb#L30-L40) needs to be able to tell a client which curves are allowed to be uploaded and the input which will be overwritten when doing so.

This...

* Allows us to show a dynamic list of curve upload options in ETModel, rather than having to hard-code the list.
* Allows us to disable the affected input whenever a curve has been uploaded.
