### ISSUE TITLE
Fix broken tests for merit order

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etengine#439]
@ChaelKruip broke them... I'll also look into it when I have time:

```
Failures:

  1) Qernel::Plugins::MeritOrder::LoadProfileTable#residual_load_profiles#residual_load_profiles
     Failure/Error: @tbl.send(:residual_load_profiles).should == [
     NoMethodError:
       undefined method `values' for nil:NilClass
     # ./app/models/qernel/plugins/merit_order.rb:214:in `must_run_merit_order_converters'
     # ./app/models/qernel/plugins/merit_order.rb:207:in `must_run_merit_order_converters'
     # ./app/models/qernel/plugins/merit_order.rb:279:in `merit_order_must_run_loads'
     # ./app/models/qernel/plugins/merit_order.rb:254:in `residual_load_profiles'
     # ./spec/models/qernel/plugins/merit_order_spec.rb:110:in `block (3 levels) in <module:MeritOrder>'

  2) Qernel::Plugins::MeritOrder::LoadProfileTable#residual_load_profiles#residual_ldc_coordinates
     Failure/Error: points = @tbl.residual_ldc_coordinates
     NoMethodError:
       undefined method `values' for nil:NilClass
     # ./app/models/qernel/plugins/merit_order.rb:214:in `must_run_merit_order_converters'
     # ./app/models/qernel/plugins/merit_order.rb:207:in `must_run_merit_order_converters'
     # ./app/models/qernel/plugins/merit_order.rb:279:in `merit_order_must_run_loads'
     # ./app/models/qernel/plugins/merit_order.rb:254:in `residual_load_profiles'
     # ./app/models/qernel/plugins/merit_order.rb:191:in `residual_ldc_coordinates'
     # ./spec/models/qernel/plugins/merit_order_spec.rb:119:in `block (3 levels) in <module:MeritOrder>'
```
